### ISSUE TITLE
Is this based on what I did?

### ISSUE THREAD

**Issue by leo60228** [wchill/SwitchInputEmulator#1]
I made something almost exactly like this (except without the TwitchPlays aspect) all the way back in January, and posted a video to ReSwitched. I didn't finish it before my HDD died, so it's not open source (if you want, I can link the video, but I don't have it right now). It's fine right now, but if you got the idea from my video, could you credit me in the README?

**Comment by wchill** [comment]
This is more or less an original idea (well, as original as a Twitch Plays can be). All code except parts of the base controller code are completely original, and even the controller code has been heavily modified. I didn't actually see any such video in RS so I have no idea what you're referring to specifically...

**Comment by leo60228** [comment]
Okay. I'll try to find it later. The video is from January; sorry if that was confusing.

**Comment by wchill** [comment]
Closing for now
