### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by IAMSolaara** [wchill/SwitchInputEmulator#16]
The project site seems to not work anymore (gives DNS_PROBE_FINISHED_NXDOMAIN error) I don't know how to use this thing. I just programmed the .hex file into the 16u2 chip on my UNO R3.

**Comment by kupokappa** [comment]
You need a USB to UART bridge. Someone else responded to an issue on this repo with the correct wiring, and there's probably some resources out there that'll tell you what to do for your specific adapter. I'm using a Silicon Labs CP210x USB to UART adapter. Wiring into an Arduino Uno R3 goes as follows (USB to UART -> Arduino):

DTR -> RESET
RXD -> RX
TXD -> TX
5V -> 5V
CTS -> GND
GND -> GND

From there, you can just use the example client.py.

**Comment by INobody95** [comment]
Hello,
after flashing the Arduino while waiting for my ordered CP2102 USB to UART adapter I honestly got not idea what to to next? Wiring from your post above and then? What file do I have to open (client.py in console?) and what to plug in where?
Native Arduino USB into the switch dock, USBtoUART into PC, Controller into PC?

**Comment by danvx6** [comment]
> 
> 
> You need a USB to UART bridge. Someone else responded to an issue on this repo with the correct wiring, and there's probably some resources out there that'll tell you what to do for your specific adapter. I'm using a Silicon Labs CP210x USB to UART adapter. Wiring into an Arduino Uno R3 goes as follows (USB to UART -> Arduino):
> 
> DTR -> RESET
> RXD -> RX
> TXD -> TX
> 5V -> 5V
> CTS -> GND
> GND -> GND
> 
> From there, you can just use the example client.py.

I think I may have bought the wrong kind of UART adapter, my pins are labeled:
3V3
GND
TXD
RXD
GND
5V

This is the adapter in question: (https://www.amazon.co.jp/-/en/gp/product/B072K3Z3TL/ref=ppx_od_dt_b_asin_title_s01?ie=UTF8&psc=1])

It does not have DTR or CTS pins. Will it still be usable for this project?

**Comment by wchill** [comment]
DTR and CTS are not needed. What you have is fine, just ignore the pins you don't have
