### ISSUE TITLE
Compatibility with ESP8266?

### ISSUE THREAD

**Issue by caribbeanwebdev** [wchill/SwitchInputEmulator#18]
How i can make this compatible with ESP8266?

**Comment by wchill** [comment]
I don't think it is possible with ESP8266, as it has no hardware USB support. You can try using ESPUSB to get software support for low-speed USB, but I am not sure if that will work for this and you will probably have to redo most of the work done here even if it does.

**Comment by caribbeanwebdev** [comment]
Thank you for take your time to answer me, i looked for some info of ESPUSB but i prefer to buy an arduino
