### ISSUE TITLE
Fails to sync

### ISSUE THREAD

**Issue by k-k-karma** [wchill/SwitchInputEmulator#7]
Hi. I'm using your software on a Arduino Leonardo board with a CP2012 USB to TTL adapter. I'm unable to use the python client to sync with my switch as it hangs on the waiting for data part. Do you know what could cause this?

**Comment by wchill** [comment]
Unfortunately I didn't write that python script. I believe @IBNobody mentioned there was a bug in it though

**Comment by k-k-karma** [comment]
Thanks, I believe this is related to all wired controllers suddenly not being detected by my switch.
